include(../../linux-g++/qmake.conf)
QMAKE_CC = x86_64-elf-gcc
QMAKE_CXX = x86_64-elf-g++
QMAKE_LINK = x86_64-elf-g++
QMAKE_AR = x86_64-elf-ar cqs
QMAKE_OBJCOPY = x86_64-elf-objcopy
QMAKE_STRIP = x86_64-elf-strip
