/* Generated by tools/update_guest_resource_holder_va.sh after desktop.elf link. */
#define BFREE_GUEST_QT_RESOURCE_HOLDER_VA 0u
#define BFREE_DESKTOP_MAIN_TLS_VA 0u
#define BFREE_DESKTOP_MAIN_TLS_BYTES 48u
