#!/usr/bin/env python3
"""Split spinner, trim white, scale, emit guest_splash_data.cpp for FB blit."""
from pathlib import Path
from PIL import Image

ASSETS = Path("/mnt/c/Users/h_kis/.cursor/projects/c-Users-h-kis-Desktop-B-Free-master-Program-bfree-x86-64/assets")
SPIN = ASSETS / "c__Users_h_kis_AppData_Roaming_Cursor_User_workspaceStorage_empty-window_images_____-132b43ad-94fd-4fd3-b5c0-652ca617e5b0.png"
LOGO = ASSETS / "c__Users_h_kis_AppData_Roaming_Cursor_User_workspaceStorage_empty-window_images_ROGO_BFREE_TRON-74bcb7f1-9dd8-4537-9594-31f71fc7252e.png"
OUT = Path("/mnt/c/Users/h_kis/Desktop/B-Free-master/Program/bfree_x86_64/userland/desktop_qt/splash")
CPP = Path("/mnt/c/Users/h_kis/Desktop/B-Free-master/Program/bfree_x86_64/userland/desktop_qt/guest_splash_data.cpp")
HDR = Path("/mnt/c/Users/h_kis/Desktop/B-Free-master/Program/bfree_x86_64/userland/desktop_qt/guest_splash_data.h")

OUT.mkdir(parents=True, exist_ok=True)

def white_to_alpha(im: Image.Image, thr=245) -> Image.Image:
    im = im.convert("RGBA")
    px = im.load()
    w, h = im.size
    for y in range(h):
        for x in range(w):
            r, g, b, a = px[x, y]
            if r >= thr and g >= thr and b >= thr:
                px[x, y] = (255, 255, 255, 0)
    return im

def tight(im: Image.Image) -> Image.Image:
    bbox = im.getbbox()
    return im.crop(bbox) if bbox else im

def to_argb_list(im: Image.Image):
    im = im.convert("RGBA")
    w, h = im.size
    px = im.load()
    out = []
    for y in range(h):
        for x in range(w):
            r, g, b, a = px[x, y]
            out.append((a << 24) | (r << 16) | (g << 8) | b)
    return w, h, out

def emit_array(name, w, h, pixels, f):
    f.write(f"static const unsigned {name}_w = {w}u;\n")
    f.write(f"static const unsigned {name}_h = {h}u;\n")
    f.write(f"static const uint32_t {name}_px[{w * h}] = {{\n")
    for i, v in enumerate(pixels):
        if i % 8 == 0:
            f.write("  ")
        f.write(f"0x{v:08X},")
        if i % 8 == 7:
            f.write("\n")
        else:
            f.write(" ")
    if len(pixels) % 8:
        f.write("\n")
    f.write("};\n\n")

im = Image.open(SPIN).convert("RGBA")
W, H = im.size
cols, rows = 2, 5
cw, rh = W // cols, H // rows
frames = []
for r in range(rows):
    for c in range(cols):
        cell = im.crop((c * cw, r * rh, (c + 1) * cw, (r + 1) * rh))
        cell = tight(white_to_alpha(cell))
        # Scale spinner to ~56px for splash under logo
        cell = cell.resize((56, 56), Image.Resampling.LANCZOS)
        cell = tight(white_to_alpha(cell, thr=250))
        idx = r * cols + c
        cell.save(OUT / f"spinner_{idx:02d}.png")
        frames.append(cell)
        print(f"spinner_{idx:02d} {cell.size}")

logo = tight(white_to_alpha(Image.open(LOGO)))
# Fit logo width ~280 for 1024 splash
lw = 280
lh = max(1, int(logo.height * lw / logo.width))
logo = logo.resize((lw, lh), Image.Resampling.LANCZOS)
logo = tight(white_to_alpha(logo, thr=250))
logo.save(OUT / "bfree_tron_logo.png")
print(f"logo {logo.size}")

with HDR.open("w", encoding="utf-8") as f:
    f.write("#pragma once\n#include <stdint.h>\n")
    f.write("#ifdef __cplusplus\nextern \"C\" {\n#endif\n")
    f.write("void guest_splash_show(unsigned frame);\n")
    f.write("void guest_splash_advance(void);\n")
    f.write("#ifdef __cplusplus\n}\n#endif\n")

with CPP.open("w", encoding="utf-8", newline="\n") as f:
    f.write("/* Auto-generated by tools/_tmp_split_splash_assets.py — do not edit. */\n")
    f.write("#include \"guest_splash_data.h\"\n")
    f.write("#include <stdint.h>\n")
    f.write("#include <cstddef>\n")
    f.write("#include <cstdint>\n\n")
    f.write("#ifndef BFREE_FB0_USER_MMAP_BASE\n")
    f.write("#define BFREE_FB0_USER_MMAP_BASE 0x01400000u\n")
    f.write("#endif\n\n")

    lw, lh, lp = to_argb_list(logo)
    emit_array("g_splash_logo", lw, lh, lp, f)
    f.write(f"static const unsigned g_splash_nframes = {len(frames)}u;\n")
    for i, fr in enumerate(frames):
        w, h, px = to_argb_list(fr)
        emit_array(f"g_splash_sp{i:02d}", w, h, px, f)

    f.write("static const uint32_t *const g_splash_sp_px[] = {\n")
    for i in range(len(frames)):
        f.write(f"  g_splash_sp{i:02d}_px,\n")
    f.write("};\n")
    f.write("static const unsigned g_splash_sp_w[] = {\n  ")
    f.write(", ".join(f"g_splash_sp{i:02d}_w" for i in range(len(frames))))
    f.write("\n};\n")
    f.write("static const unsigned g_splash_sp_h[] = {\n  ")
    f.write(", ".join(f"g_splash_sp{i:02d}_h" for i in range(len(frames))))
    f.write("\n};\n\n")

    f.write("""static unsigned g_splash_frame = 0;

static void splash_put(unsigned char *fb, unsigned pitch, int x, int y, uint32_t argb)
{
    if ((unsigned)x >= 1024u || (unsigned)y >= 768u)
        return;
    if ((argb >> 24) < 8u)
        return; /* skip near-transparent */
    auto *p = reinterpret_cast<uint32_t *>(fb + (unsigned)y * pitch + (unsigned)x * 4u);
    *p = argb | 0xFF000000u;
}

static void splash_blit(unsigned char *fb, unsigned pitch, int dst_x, int dst_y,
                        const uint32_t *src, unsigned sw, unsigned sh)
{
    for (unsigned y = 0; y < sh; ++y) {
        for (unsigned x = 0; x < sw; ++x) {
            splash_put(fb, pitch, dst_x + (int)x, dst_y + (int)y, src[y * sw + x]);
        }
    }
}

extern "C" void guest_splash_show(unsigned frame)
{
    auto *fb = reinterpret_cast<unsigned char *>(static_cast<uintptr_t>(BFREE_FB0_USER_MMAP_BASE));
    const unsigned pitch = 1024u * 4u;
    /* White band only (avoid early-boot FB map edge PF on full 768 clear). */
    const unsigned y0 = 260u;
    const unsigned y1 = 560u;
    for (unsigned y = y0; y < y1; ++y) {
        auto *row = reinterpret_cast<uint32_t *>(fb + y * pitch);
        for (unsigned x = 0; x < 1024u; ++x)
            row[x] = 0xFFFFFFFFu;
    }
    const int logo_x = (1024 - (int)g_splash_logo_w) / 2;
    const int logo_y = 384 + 24;
    splash_blit(fb, pitch, logo_x, logo_y, g_splash_logo_px, g_splash_logo_w, g_splash_logo_h);
    if (g_splash_nframes == 0)
        return;
    unsigned fi = frame % g_splash_nframes;
    const unsigned sw = g_splash_sp_w[fi];
    const unsigned sh = g_splash_sp_h[fi];
    const int sp_x = (1024 - (int)sw) / 2;
    const int sp_y = logo_y + (int)g_splash_logo_h + 28;
    splash_blit(fb, pitch, sp_x, sp_y, g_splash_sp_px[fi], sw, sh);
    g_splash_frame = fi;
}

extern "C" void guest_splash_advance(void)
{
    g_splash_frame = (g_splash_frame + 1u) % (g_splash_nframes ? g_splash_nframes : 1u);
    guest_splash_show(g_splash_frame);
}
""")

print("wrote", CPP, HDR)
# size estimate
print("cpp bytes", CPP.stat().st_size)
