#!/usr/bin/env python3
"""Emit kernel/fb_splash_brand_data.{c,h} from desktop_qt/splash PNGs."""
from pathlib import Path
from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
SPLASH = ROOT / "userland/desktop_qt/splash"
OUT_C = ROOT / "kernel/fb_splash_brand_data.c"
OUT_H = ROOT / "kernel/fb_splash_brand_data.h"


def to_argb(im: Image.Image):
    im = im.convert("RGBA")
    w, h = im.size
    px = im.load()
    out = []
    for y in range(h):
        for x in range(w):
            r, g, b, a = px[x, y]
            out.append((a << 24) | (r << 16) | (g << 8) | b)
    return w, h, out


def emit(name, w, h, pixels, f):
    f.write(f"const unsigned {name}_w = {w}u;\n")
    f.write(f"const unsigned {name}_h = {h}u;\n")
    f.write(f"const uint32_t {name}_px[{w * h}] = {{\n")
    for i, v in enumerate(pixels):
        if i % 8 == 0:
            f.write("  ")
        f.write(f"0x{v:08X},")
        f.write("\n" if i % 8 == 7 else " ")
    if len(pixels) % 8:
        f.write("\n")
    f.write("};\n\n")


def main():
    logo = Image.open(SPLASH / "bfree_tron_logo.png")
    frames = [Image.open(SPLASH / f"spinner_{i:02d}.png") for i in range(10)]

    with OUT_H.open("w", encoding="utf-8", newline="\n") as f:
        f.write("#pragma once\n#include <stdint.h>\n")
        f.write("extern const unsigned g_brand_logo_w;\n")
        f.write("extern const unsigned g_brand_logo_h;\n")
        f.write("extern const uint32_t g_brand_logo_px[];\n")
        f.write("extern const unsigned g_brand_nframes;\n")
        f.write("extern const uint32_t *const g_brand_sp_px[];\n")
        f.write("extern const unsigned g_brand_sp_w[];\n")
        f.write("extern const unsigned g_brand_sp_h[];\n")

    with OUT_C.open("w", encoding="utf-8", newline="\n") as f:
        f.write("/* Auto-generated by tools/_tmp_gen_kernel_brand_splash.py */\n")
        f.write('#include "fb_splash_brand_data.h"\n\n')
        lw, lh, lp = to_argb(logo)
        emit("g_brand_logo", lw, lh, lp, f)
        f.write(f"const unsigned g_brand_nframes = {len(frames)}u;\n")
        for i, fr in enumerate(frames):
            w, h, px = to_argb(fr)
            emit(f"g_brand_sp{i:02d}", w, h, px, f)
        f.write("const uint32_t *const g_brand_sp_px[] = {\n")
        for i in range(len(frames)):
            f.write(f"  g_brand_sp{i:02d}_px,\n")
        f.write("};\n")
        f.write("const unsigned g_brand_sp_w[] = {\n  ")
        f.write(", ".join(f"g_brand_sp{i:02d}_w" for i in range(len(frames))))
        f.write("\n};\n")
        f.write("const unsigned g_brand_sp_h[] = {\n  ")
        f.write(", ".join(f"g_brand_sp{i:02d}_h" for i in range(len(frames))))
        f.write("\n};\n")

    print(f"wrote {OUT_C} ({OUT_C.stat().st_size} bytes)")
    print(f"logo {logo.size}")


if __name__ == "__main__":
    main()
