#!/usr/bin/env python3
"""Emit guest_mvp_shell_qml.inc from iso_root GuestMvpShell.qml (no QFile/QResource on guest)."""
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
# Guest embed uses smoke QML (QtObject). Full Window MVP stays in iso_root for host demo.
src = (ROOT / "userland/desktop_qt/GuestMvpShell_smoke.qml").read_bytes()
out = ROOT / "userland/desktop_qt/guest_mvp_shell_qml.inc"
lines = [
    "/* Generated by tools/gen_guest_mvp_shell_bytes.py — do not edit */",
    f"static const unsigned char kGuestMvpShellQml[{len(src)}] = {{",
]
for i in range(0, len(src), 16):
    chunk = src[i : i + 16]
    hexes = ", ".join(f"0x{b:02x}" for b in chunk)
    lines.append(f"    {hexes},")
lines.append("};")
out.write_text("\n".join(lines) + "\n", encoding="utf-8")
print(f"[gen_guest_mvp_shell_bytes] {len(src)} bytes -> {out}")
