#!/usr/bin/env bash
# Guest Qt + DesktopShell.qml — porting checklist (no heavy build inside this script).
# Product policy: shipping UX is guest framebuffer + QML (see GUEST_QT_DESKTOP.txt).
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
echo "[guest_qt] Policy: end-user session = guest Qt + DesktopShell.qml on fbdev (not host-only)."
echo "[guest_qt] B-Free root: $ROOT"
echo "[guest_qt] Read: $ROOT/GUEST_QT_DESKTOP.txt"
echo ""
echo "Phase 1 — Host QPA (already in tree)"
echo "  cd $ROOT/gui_server/integration_gui/bfree_qpa && qmake6 qpa_bfree.pro && make -j\$(nproc)"
echo ""
echo "Phase 2 — Cross Qt (not automated): pick ONE"
echo "  A) Static Qt6 + qmlscene linked for x86_64-none-elf + B-Free syscalls only"
echo "  B) musl/embedded Linux userland inside QEMU (different product shape)"
echo ""
echo "Phase B — Guest Qt + bfree QPA + minimal QML (do in order; each step is its own task)"
echo "  B1  Host baseline: build libqbfree.so; run bfree_qpa/test build_and_run_smoke.sh on Linux/WSL"
echo "       (confirms plugin + event path before any cross work)."
echo "  B2  Syscall audit: see bfree_qpa/bfree/bfree_guest_abi.h + bfree_qpa_config.h (window syscalls"
echo "       off by default; Linux skips /dev/fb0 TK2 path; guest input: qmake CONFIG+=guestinput)."
echo "  B3  Toolchain (DECIDED in-tree default: 2-A). Read GUEST_QT_DESKTOP.txt section"
echo "       \"B3 Toolchain decision\". Record on your machine:"
echo "       BFREE_GUEST_CC / BFREE_GUEST_LD, BFREE_QT_BUILD_DIR (out-of-tree Qt build)."
echo "       Optional side track: 2-B = Linux/musl in QEMU — not the shipping ABI."
echo "  B4a In-tree: make -C userland/desktop_b4_probe && rebuild ISO; GRUB entry"
echo "       \"GUI — B4 probe replaces desktop.elf slot\". Serial [B4] lines = pass."
echo "  B4b Guest Qt: static QtCore + bfree QPA in same ELF slot; see B3 BFREE_QT_BUILD_DIR."
echo "  B5  Add Qt Quick + one Smoke.qml; ship .so + qml + imports in initrd next to desktop.elf;"
echo "       grow ISO/initrd budget; set QT_QUICK_BACKEND=software unless guest GL exists."
echo "  B6  Hardening: argv/env for exec_initrd, unmap old init mappings, crash logs on serial."
echo ""
echo "Phase 3 — Kernel exec_initrd (syscall 41)"
echo "  In tree: load named initrd ELF + SYSRET into ring3 (see sys_exec_initrd, syscall_entry.S)."
echo "  Next: unmap/replace init mappings, argv/env, verify desktop.elf for strict boot."
echo ""
echo "Phase 4 — Replace desktop_stub.c with real launcher entry (DesktopShell.qml root path)."
echo "[guest_qt] Done (informational)."
