#!/usr/bin/env bash
# Write a minimal libtool .lo manifest pointing at a plain .o (disable-shared static build).
set -euo pipefail
lo="$1"
obj="$2"
cat >"$lo" <<EOF
# $lo - a libtool object file
# Generated by bfree mk_libtool_lo.sh

# Name of the PIC object.
pic_object=none

# Name of the non-PIC object.
non_pic_object='$obj'
EOF
